"""`roles claim` under a store that is DOWN, not empty.

THE INCIDENT, 2026-09-04 ~01:16Z-02:14Z. The Fulcra file plane returned HTTP
500 for every path three levels deep or more, globally — depth <= 2 kept
working and the annotation plane was untouched. `transport.read` collapses
"absent" and "unreadable" into None and `transport.write` returns a False that
nobody read, so this one verb did three wrong things in a single invocation:

  * printed "role 'coord-boss' has no registered role doc" while that doc sat
    in the store at 1390 bytes, unchanged since 2026-08-03 (proved by `file
    stat` once the plane recovered). That message is not cosmetic: it says
    dormancy suppression and review role-routing are off for the role.
  * printed "claimed coord-boss" and exited 0 for a write that never landed.
    The shard's version history runs 01:14:22Z straight to 02:14:45Z — there
    is no version in between.
  * wrote the phantom nonce to LOCAL state, so the next real claim reported
    "another session last claimed as coord-boss 1h ago (same-id
    double-acting)" — a false intruder alarm generated by our own lost write.

Same rule on both planes: an unreadable read is UNKNOWN, never absence, and an
unverified write is not a claim.
"""

from __future__ import annotations

import datetime

import pytest

from coord_engine import cli
from coord_engine_test_helpers import FakeTransport

TEAM = "acme"
AGENT = "coord-boss"
ROLE = "coord-boss"
ROLE_DOC = f"team/{TEAM}/roles/{ROLE}.md"
SHARD = f"team/{TEAM}/roles/{ROLE}/leases/{ROLE}.md"


@pytest.fixture(autouse=True)
def _pin_clock_and_state(monkeypatch, tmp_path):
    monkeypatch.setattr(cli, "_now", lambda: datetime.datetime(
        2026, 9, 4, 2, 0, 0, tzinfo=datetime.timezone.utc))
    monkeypatch.setenv("COORD_ENGINE_STATE_DIR", str(tmp_path / "state"))
    monkeypatch.setenv("FULCRA_COORD_AGENT", AGENT)


def _role_doc():
    return "\n".join(["---", "type: Role", f"title: {ROLE}", f"role: {ROLE}",
                      "maintainer: coord-boss", "---", "", "# role", ""])


class DeepPathsDown(FakeTransport):
    """The measured outage shape: depth >= 3 errors, everything else works."""

    def __init__(self, *, fail_writes=True):
        super().__init__()
        self.fail_writes = fail_writes
        self.write_attempts: list[str] = []

    @staticmethod
    def _deep(path):
        return path.count("/") >= 3

    def read_classified(self, path, *, deadline=None):
        if self._deep(path):
            return None, "error"
        return super().read_classified(path)

    def read(self, path):
        return None if self._deep(path) else super().read(path)

    def write(self, path, content):
        self.write_attempts.append(path)
        if self.fail_writes and self._deep(path):
            return False
        return super().write(path, content)


def _claim(transport):
    return cli.main(["roles", "claim", TEAM, ROLE], transport=transport)


def test_an_unreadable_role_doc_is_UNKNOWN_not_a_missing_one(capsys):
    """The claim that started the incident. The doc existed; the read did not."""
    t = DeepPathsDown()
    t.put(ROLE_DOC, _role_doc())
    _claim(t)
    err = capsys.readouterr().err
    assert "UNKNOWN, not absence" in err
    assert "has no registered role doc" not in err


def test_a_genuinely_absent_role_doc_still_says_so(capsys):
    """The fix must not blunt the real message: absence is still absence."""
    t = FakeTransport()
    _claim(t)
    err = capsys.readouterr().err
    assert "has no registered role doc" in err
    assert "UNKNOWN, not absence" not in err


def test_a_write_that_did_not_land_is_NOT_reported_as_a_claim(capsys):
    t = DeepPathsDown()
    t.put(ROLE_DOC, _role_doc())
    rc = _claim(t)
    out, err = capsys.readouterr()
    assert rc == 3
    assert "WRITE FAILED" in err
    assert "claimed coord-boss" not in out


def test_a_failed_write_does_NOT_poison_the_local_nonce_state(capsys, tmp_path):
    """The false-intruder alarm came from here. If the store never saw the
    nonce, the next claim comparing against it manufactures a mismatch."""
    t = DeepPathsDown()
    t.put(ROLE_DOC, _role_doc())
    _claim(t)
    state_dir = tmp_path / "state"
    written = list(state_dir.glob("lease-nonce-*")) if state_dir.exists() else []
    assert written == [], written


def test_a_write_that_DOES_land_still_claims_and_records_its_nonce(capsys, tmp_path):
    """The positive control: with a healthy store the verb is unchanged."""
    t = FakeTransport()
    t.put(ROLE_DOC, _role_doc())
    rc = _claim(t)
    out = capsys.readouterr().out
    assert rc == 0 and "claimed coord-boss" in out
    assert list((tmp_path / "state").glob("lease-nonce-*"))


def test_an_unreadable_shard_says_the_double_acting_check_did_not_run(capsys):
    """'Check disabled' must never be presented as 'check passed'."""
    t = DeepPathsDown(fail_writes=False)
    t.put(ROLE_DOC, _role_doc())
    _claim(t)
    err = capsys.readouterr().err
    assert "double-acting check did NOT run" in err
