"""Trakt OAuth handler for fulcra-collect's generic OAuth flow.

Called by the daemon's /api/oauth/trakt/callback route after the user
has authorized Fulcra Collect in their Trakt account. Exchanges the
authorization code (plus the PKCE code_verifier) for access and refresh
tokens, which the callback route then stores in the plugin's keychain
namespace.

The Trakt client_id and client_secret are expected to have been stored in
the keychain already (via the "input" SetupStep that precedes the "oauth"
step in TRAKT_PLUGIN.setup_steps).

Why PKCE with Trakt?
  Trakt's /oauth/token endpoint accepts the code_verifier parameter as of
  their current API version and will validate it if provided. Using PKCE
  makes the authorization code useless even if intercepted in transit.
"""
from __future__ import annotations

import httpx

TRAKT_TOKEN_ENDPOINT = "https://api.trakt.tv/oauth/token"


def trakt_oauth_handler(
    *,
    plugin_id: str,
    code: str,
    code_verifier: str,
    redirect_uri: str,
) -> dict[str, str]:
    """Exchange a Trakt authorization code for access + refresh tokens.

    Arguments are passed by the daemon's oauth_callback route via keyword:
      plugin_id     — the plugin's credential namespace in the keychain
      code          — the authorization code from the OAuth callback URL
      code_verifier — the PKCE code verifier generated by start_flow()
      redirect_uri  — the exact redirect URI used in the authorization request

    Returns a dict suitable for the callback route to persist:
      {"access_token": "...", "refresh_token": "...", "expires_in": "...",
       "created_at": "..."}

    Raises RuntimeError when the Trakt client credentials are not yet in
    the keychain (i.e., the user skipped the "Paste your credentials" step).
    Raises httpx.HTTPStatusError when Trakt's token endpoint rejects the
    exchange request.
    """
    from fulcra_collect import credentials as _creds

    client_id = _creds.get_secret(plugin_id, "client_id")
    client_secret = _creds.get_secret(plugin_id, "client_secret")
    if not client_id or not client_secret:
        raise RuntimeError(
            "trakt: client_id / client_secret not configured — "
            "complete the 'Paste your Trakt OAuth credentials' step first"
        )

    payload = {
        "code": code,
        "client_id": client_id,
        "client_secret": client_secret,
        "redirect_uri": redirect_uri,
        "grant_type": "authorization_code",
        "code_verifier": code_verifier,
    }
    with httpx.Client(timeout=15.0) as client:
        r = client.post(TRAKT_TOKEN_ENDPOINT, json=payload)
        r.raise_for_status()
        body = r.json()

    return {
        "access_token": body.get("access_token", ""),
        "refresh_token": body.get("refresh_token", ""),
        "expires_in": str(body.get("expires_in", "")),
        "created_at": str(body.get("created_at", "")),
    }
