"""Release bundles must not retain paths from the build machine."""
import importlib.util
from pathlib import Path

import pytest

SCRIPT = Path(__file__).parents[1] / 'scripts' / 'sanitize_bundle.py'


def _module():
    spec = importlib.util.spec_from_file_location('sanitize_bundle', SCRIPT)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _app(tmp_path):
    app = tmp_path / 'Collect.app'
    (app / 'Contents/Resources/app_packages').mkdir(parents=True)
    return app


def test_removes_nonportable_pip_scripts_but_preserves_native_launchers(tmp_path):
    app = _app(tmp_path)
    pip_bin = app / 'Contents/Resources/app_packages/bin'
    pip_bin.mkdir()
    (pip_bin / 'fulcra').write_text('#!/Users/tester/build/python\n')
    native_bin = app / 'Contents/MacOS'
    native_bin.mkdir()
    launcher = native_bin / 'fulcra'
    launcher.write_bytes(b'native launcher')
    _module().sanitize(app, home=Path('/Users/tester'))
    assert not pip_bin.exists()
    assert launcher.read_bytes() == b'native launcher'


def test_removes_generated_bytecode_before_privacy_check(tmp_path):
    app = _app(tmp_path)
    package = app / 'Contents/Resources/app_packages/example'
    cache = package / '__pycache__'
    cache.mkdir(parents=True)
    source = package / 'module.py'
    source.write_text('VALUE = 1\n')
    (cache / 'module.cpython-313.pyc').write_bytes(
        b'compiled from /Users/tester/build/module.py'
    )

    _module().sanitize(app, home=Path('/Users/tester'))

    assert not cache.exists()
    assert source.read_text() == 'VALUE = 1\n'


def test_check_only_rejects_generated_bytecode_without_deleting_it(tmp_path):
    app = _app(tmp_path)
    cache = app / 'Contents/Resources/app_packages/example/__pycache__'
    cache.mkdir(parents=True)
    bytecode = cache / 'module.cpython-313.pyc'
    bytecode.write_bytes(b'compiled code')

    with pytest.raises(RuntimeError, match='Generated bytecode remains'):
        _module().sanitize(app, check_only=True)

    assert bytecode.exists()


@pytest.mark.parametrize('dangling', [False, True])
def test_refuses_cached_bytecode_symlinks_before_deleting_any_cache(tmp_path, dangling):
    app = _app(tmp_path)
    cache = app / 'Contents/Resources/app_packages/example/__pycache__'
    cache.mkdir(parents=True)
    ordinary_bytecode = cache / 'ordinary.cpython-313.pyc'
    ordinary_bytecode.write_bytes(b'compiled code')
    outside = tmp_path / 'outside.pyc'
    if not dangling:
        outside.write_bytes(b'keep outside')
    linked_bytecode = cache / 'linked.cpython-313.pyc'
    linked_bytecode.symlink_to(outside)

    with pytest.raises(RuntimeError, match='symlinked generated bytecode'):
        _module().sanitize(app, home=Path('/Users/tester'))

    assert cache.is_dir()
    assert ordinary_bytecode.read_bytes() == b'compiled code'
    assert linked_bytecode.is_symlink()
    if not dangling:
        assert outside.read_bytes() == b'keep outside'


def test_rejects_builder_home_in_binary_metadata_without_printing_it(tmp_path):
    app = _app(tmp_path)
    leak = app / 'Contents/Resources/metadata.bin'
    leak.write_bytes(b'\x00' + b'/Users/tester/build/cache' + b'\x00')
    with pytest.raises(RuntimeError) as error:
        _module().sanitize(app, home=Path('/Users/tester'))
    assert '1 bundle entries' in str(error.value)
    assert '/Users/tester' not in str(error.value)


def test_refuses_to_remove_a_symlinked_script_directory(tmp_path):
    app = _app(tmp_path)
    outside = tmp_path / 'outside'
    outside.mkdir()
    (outside / 'keep').write_text('keep')
    (app / 'Contents/Resources/app_packages/bin').symlink_to(outside)
    with pytest.raises(RuntimeError):
        _module().sanitize(app, home=Path('/Users/tester'))
    assert (outside / 'keep').exists()


@pytest.mark.parametrize('encoding', ['utf-8', 'utf-16-le', 'utf-16-be'])
def test_rejects_bare_home_and_utf16_paths(tmp_path, encoding):
    app = _app(tmp_path)
    (app / 'Contents/Resources/file').write_bytes('/Users/tester'.encode(encoding))
    with pytest.raises(RuntimeError):
        _module().sanitize(app, home=Path('/Users/tester'))


def test_rejects_symlink_target_without_following_it(tmp_path):
    app = _app(tmp_path)
    (app / 'Contents/Resources/link').symlink_to('/Users/tester/private')
    with pytest.raises(RuntimeError):
        _module().sanitize(app, home=Path('/Users/tester'))


def test_check_only_cannot_delete_new_build_scripts(tmp_path):
    app = _app(tmp_path)
    scripts = app / 'Contents/Resources/app_packages/bin'
    scripts.mkdir()
    with pytest.raises(RuntimeError):
        _module().sanitize(app, check_only=True)
    assert scripts.exists()


def test_removes_dependency_test_payloads_but_preserves_runtime_packages(tmp_path):
    app = _app(tmp_path)
    packages = app / 'Contents/Resources/app_packages'
    test_payloads = [
        packages / 'PyObjCTest/case.py',
        packages / '_pytest/main.py',
        packages / 'pytest/__init__.py',
        packages / 'pytest-7.4.4.dist-info/METADATA',
        packages / 'pandas/tests/test_frame.py',
        packages / 'numpy/lib/tests/test_shape.py',
        packages / 'pyarrow/_pyarrow_cpp_tests.cpython-313-darwin.so',
    ]
    for path in test_payloads:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text('test-only')
    runtime = packages / 'numpy/testing/__init__.py'
    runtime.parent.mkdir(parents=True)
    runtime.write_text('public runtime helper')

    _module().sanitize(app, home=Path('/Users/tester'))

    assert all(not path.exists() for path in test_payloads)
    assert runtime.read_text() == 'public runtime helper'


def test_check_only_rejects_dependency_test_payloads_without_deleting_them(tmp_path):
    app = _app(tmp_path)
    test_module = app / 'Contents/Resources/app_packages/pandas/tests/test_frame.py'
    test_module.parent.mkdir(parents=True)
    test_module.write_text('test-only')

    with pytest.raises(RuntimeError, match='Test-only payloads remain'):
        _module().sanitize(app, check_only=True)

    assert test_module.exists()


def test_refuses_symlinked_test_payload_before_deleting_anything(tmp_path):
    app = _app(tmp_path)
    packages = app / 'Contents/Resources/app_packages'
    ordinary = packages / 'PyObjCTest/case.py'
    ordinary.parent.mkdir(parents=True)
    ordinary.write_text('test-only')
    outside = tmp_path / 'outside-tests'
    outside.mkdir()
    (outside / 'keep').write_text('keep')
    (packages / 'example').mkdir()
    (packages / 'example/tests').symlink_to(outside, target_is_directory=True)

    with pytest.raises(RuntimeError, match='symlinked test-only payload'):
        _module().sanitize(app, home=Path('/Users/tester'))

    assert ordinary.exists()
    assert (outside / 'keep').read_text() == 'keep'

@pytest.mark.parametrize('check_only', [False, True])
def test_refuses_symlinked_pyarrow_parent_without_touching_outside(tmp_path, check_only):
    app = _app(tmp_path)
    packages = app / 'Contents/Resources/app_packages'
    outside = tmp_path / 'outside-arrow'
    outside.mkdir()
    payload = outside / '_pyarrow_cpp_tests.synthetic.so'
    payload.write_text('must survive')
    (packages / 'pyarrow').symlink_to(outside, target_is_directory=True)
    with pytest.raises(RuntimeError, match='symlinked test-only payload'):
        _module().sanitize(app, home=Path('/Users/tester'), check_only=check_only)
    assert payload.read_text() == 'must survive'
