"""SKILL.md contract tests — pattern-doc checklist item 4 (the gap the
reference implementation itself had): pin every prose claim that code could
falsify, so drift is caught at commit time instead of in review.

Cheap-beats-clever: these are grep/parse assertions, not simulations.
"""

import json
import re
from pathlib import Path

PKG = Path(__file__).resolve().parents[1]
SKILL_DIR = PKG / "skills" / "fulcra-netflix"
SKILL = (SKILL_DIR / "SKILL.md").read_text()
REFS = {p.name: p.read_text() for p in (SKILL_DIR / "references").glob("*.md")}
ALL_PROSE = SKILL + "".join(REFS.values())


def _script_flags():
    src = (SKILL_DIR / "scripts" / "netflix_import.py").read_text()
    return set(re.findall(r'add_argument\(\s*"(--[a-z-]+)"', src))


def _prose_script_flags():
    """Flags used on netflix_import.py invocation lines in the prose — NOT
    flags for other tools (fulcra-api auth flags appear in the same docs)."""
    flags = set()
    for line in ALL_PROSE.splitlines():
        if "netflix_import.py" in line:
            flags.update(re.findall(r"(--[a-z-]+)", line))
    return flags


def test_every_documented_script_flag_exists():
    documented = _prose_script_flags()
    real = _script_flags()
    assert documented, "no netflix_import.py invocations found in prose — parser broke?"
    missing = documented - real
    assert not missing, f"SKILL prose uses flags the script lacks: {sorted(missing)}"


def test_every_script_flag_is_documented():
    # direction 2 is looser than direction 1: a flag counts as documented if it
    # is MENTIONED anywhere in the prose (invocation line or explanatory text)
    undocumented = {f for f in _script_flags() if f"`{f}`" not in ALL_PROSE and f not in ALL_PROSE}
    assert not undocumented, (
        f"script flags never mentioned in any prose: {sorted(undocumented)} — "
        "document them or remove them")


def test_five_state_machine_named_in_order():
    m = re.search(r"HELLO\s*→\s*AUTH\s*→\s*EXPORT\s*→\s*IMPORT\s*→\s*SHARE", SKILL)
    assert m, "the five-state machine line changed — update probes/states together"
    # and each state has its own section
    for state in ["HELLO", "AUTH", "EXPORT", "IMPORT", "SHARE"]:
        assert re.search(rf"^##.*\b{state}\b", SKILL, re.M), f"no section for state {state}"


def test_probe_table_commands_reference_real_tools():
    # every probe row command must invoke a tool that exists in the repo story
    rows = [l for l in SKILL.splitlines() if l.startswith("|") and "`" in l]
    assert rows, "probe table missing"
    cmds = " ".join(rows)
    assert "fulcra-api user-info" in cmds
    assert "fulcra-api catalog" in cmds


def test_record_schema_doc_matches_build_record_output():
    from fulcra_netflix import loader
    ni = loader.load()
    ev = next(iter(ni.parse_slim(PKG / "tests" / "fixtures" / "slim.csv")))
    rec = ni.build_record(ev, def_id="contract-test")
    schema_doc = REFS["record-schema.md"]

    def documented(key):
        # backticked prose mention OR quoted key in the canonical JSON example
        # (the example is generated byte-for-byte from real output — it IS doc)
        return f"`{key}`" in schema_doc or f'"{key}"' in schema_doc

    for key in rec:
        assert documented(key), f"envelope key {key!r} undocumented in record-schema.md"
    for key in rec["metadata"]:
        assert documented(key), f"metadata key {key!r} undocumented in record-schema.md"
    for key in json.loads(rec["data"]):
        assert documented(key), f"payload key {key!r} undocumented in record-schema.md"


def test_deterministic_id_claim_is_true():
    # SKILL.md: "the importer's record IDs are deterministic, so re-imports are
    # server-side no-ops" — pin the determinism half here
    assert "record IDs are deterministic" in SKILL
    from fulcra_netflix import loader
    ni = loader.load()
    evs = list(ni.parse_slim(PKG / "tests" / "fixtures" / "slim.csv"))
    assert [e.det_id for e in evs] == [e.det_id for e in
                                       ni.parse_slim(PKG / "tests" / "fixtures" / "slim.csv")]
