"""SKILL.md contract tests — pattern-doc checklist item 4 (the gap the
reference implementation itself had): pin every prose claim that code could
falsify, so drift is caught at commit time instead of in review.

Cheap-beats-clever: these are grep/parse assertions, not simulations.
"""

import json
import re
from pathlib import Path

PKG = Path(__file__).resolve().parents[1]
SKILL_DIR = PKG / "skills" / "fulcra-netflix"
SKILL = (SKILL_DIR / "SKILL.md").read_text(encoding="utf-8")
REFS = {p.name: p.read_text(encoding="utf-8")
        for p in (SKILL_DIR / "references").glob("*.md")}
ALL_PROSE = SKILL + "".join(REFS.values())

#: flags in the prose that belong to OTHER tools (fulcra-api auth), not the
#: import script — keep explicit so a typo'd script flag can't hide here
FOREIGN_FLAGS = {"--get-auth-url", "--device-code", "--poll-timeout"}


def _script_flags():
    src = (SKILL_DIR / "scripts" / "netflix_import.py").read_text(encoding="utf-8")
    return set(re.findall(r'add_argument\(\s*"(--[a-z-]+)"', src))


def _prose_flags():
    """EVERY backticked --flag anywhere in the prose (invocation lines AND
    explanatory sentences — the 'add `--flag` to...' idiom is where drift
    hid on this suite's first run)."""
    return set(re.findall(r"`(--[a-z-]+)(?:=[^`]*)?`", ALL_PROSE))  # `--flag` or `--flag=value`


def test_every_prose_flag_exists_in_script_or_allowlist():
    unknown = _prose_flags() - _script_flags() - FOREIGN_FLAGS
    assert not unknown, (
        f"prose mentions flags that are neither script flags nor allowlisted "
        f"foreign-tool flags: {sorted(unknown)}")


def test_every_script_flag_is_documented():
    undocumented = _script_flags() - _prose_flags()
    assert not undocumented, (
        f"script flags never mentioned (backticked) in any prose: "
        f"{sorted(undocumented)} — document them or remove them")


def test_foreign_allowlist_is_not_stale():
    # if a foreign flag disappears from the prose, prune the allowlist
    gone = FOREIGN_FLAGS - _prose_flags()
    assert not gone, f"allowlisted flags no longer in prose: {sorted(gone)}"


def test_five_state_machine_named_in_order():
    m = re.search(r"HELLO\s*→\s*AUTH\s*→\s*EXPORT\s*→\s*IMPORT\s*→\s*SHARE", SKILL)
    assert m, "the five-state machine line changed — update probes/states together"
    for state in ["HELLO", "AUTH", "EXPORT", "IMPORT", "SHARE"]:
        assert re.search(rf"^##.*\b{state}\b", SKILL, re.M), f"no section for state {state}"


def test_probe_table_commands_reference_real_tools():
    # anchor to the probe table specifically, not any table in the file
    start = SKILL.index("## Where to start")
    section = SKILL[start:SKILL.index("## ", start + 5)]
    rows = [l for l in section.splitlines() if l.startswith("|") and "`" in l]
    assert rows, "probe table missing from 'Where to start'"
    cmds = " ".join(rows)
    for tool in ("fulcra-api user-info", "fulcra-api catalog", "fulcra-api get-records"):
        assert tool in cmds, f"probe table lost its {tool} command"


def _wire_example():
    """The canonical wire-record JSON block in record-schema.md — the doc says
    it is generated byte-for-byte from real importer output; parse it so the
    claim is pinned, not taken on faith."""
    doc = REFS["record-schema.md"]
    start = doc.index("## Example wire record")
    block = re.search(r"```json\n(.*?)```", doc[start:], re.S)
    assert block, "wire-record example block missing"
    return json.loads(block.group(1))


def _same_key_structure(example, real, path="envelope"):
    """Recursive key-set comparison (merges the reviewer-fixer's recursion with
    the example-pinned approach): every nesting level of the documented example
    must match the live output's keys — recorded_at, external_ids, all of it."""
    assert set(example) == set(real), (
        f"key drift at {path}: example={sorted(example)} real={sorted(real)}")
    for k in example:
        if isinstance(example[k], dict) and isinstance(real[k], dict):
            _same_key_structure(example[k], real[k], f"{path}.{k}")


def test_record_schema_example_matches_build_record_keys():
    from fulcra_netflix import loader
    ni = loader.load()
    ev = next(iter(ni.parse_slim(PKG / "tests" / "fixtures" / "slim.csv")))
    rec = ni.build_record(ev, def_id="contract-test")
    example = _wire_example()
    _same_key_structure(example, rec)
    _same_key_structure(json.loads(example["data"]), json.loads(rec["data"]), "data")


def test_deterministic_id_claim_is_true():
    assert "record IDs are deterministic" in SKILL
    from fulcra_netflix import loader
    ni = loader.load()
    fixture = PKG / "tests" / "fixtures" / "slim.csv"
    assert ([e.det_id for e in ni.parse_slim(fixture)]
            == [e.det_id for e in ni.parse_slim(fixture)])
